spring:
  application:
    name: mini-pay-system
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
